#!/bin/sh
# Build Heimdall.app for macOS so the Dock and menu bar show Heimdall's
# name and icon from launch to quit.
#
# Why a bundle: `python main.py` runs inside Python.app, so macOS shows the
# Python rocket and the "Python" menu. The window can swap the Dock icon
# while it is open, but at launch and at quit macOS shows the icon of the
# bundle that owns the process. Here the process belongs to Heimdall.app.
#
# The bundle does not copy the code or the dependencies: it runs main.py
# and the .venv of this checkout, so `git pull` updates the app too.
#
# Usage, from the repo root, after creating .venv (see README):
#   sh tools/build_macos_app.sh            # -> dist/Heimdall.app
#   sh tools/build_macos_app.sh --install  # also copies it to ~/Applications
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
VENV_PY="$ROOT/.venv/bin/python"
[ -x "$VENV_PY" ] || { echo "No existe $VENV_PY. Crea el entorno primero (README)."; exit 1; }

# The real interpreter inside the framework's Python.app. Running a copy of
# it from our bundle makes Heimdall.app the process's main bundle.
BASE_PREFIX=$("$VENV_PY" -c 'import sys; print(sys.base_prefix)')
VERSION=$("$VENV_PY" -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")')
PYAPP_BIN="$BASE_PREFIX/Resources/Python.app/Contents/MacOS/Python"
[ -x "$PYAPP_BIN" ] || { echo "No encontré $PYAPP_BIN (se necesita un Python 'framework', p. ej. de Homebrew o python.org)."; exit 1; }
SITE=$("$VENV_PY" -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')
APP_VERSION=$(sed -n 's/^APP_VERSION = "\(.*\)"/\1/p' "$ROOT/main.py")

APP="$ROOT/dist/Heimdall.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$ROOT/branding/heimdall.icns" "$APP/Contents/Resources/heimdall.icns"
cp "$PYAPP_BIN" "$APP/Contents/MacOS/heimdall-python"

cat > "$APP/Contents/MacOS/Heimdall" <<EOF
#!/bin/sh
# Generated by tools/build_macos_app.sh
cd "$ROOT"
# Opened from Finder/Dock the app gets a minimal PATH without Homebrew,
# so ffmpeg and swiftc would not be found. Add the usual locations.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\$PATH"
export PYTHONHOME="$BASE_PREFIX"
export PYTHONPATH="$ROOT:$SITE"
exec "\$(dirname "\$0")/heimdall-python" "$ROOT/main.py" "\$@"
EOF
chmod +x "$APP/Contents/MacOS/Heimdall"

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Heimdall</string>
  <key>CFBundleDisplayName</key><string>Heimdall</string>
  <key>CFBundleIdentifier</key><string>com.mediaforge.heimdall</string>
  <key>CFBundleExecutable</key><string>Heimdall</string>
  <key>CFBundleIconFile</key><string>heimdall.icns</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$APP_VERSION</string>
  <key>CFBundleVersion</key><string>$APP_VERSION</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
EOF

# Ad-hoc signature so Gatekeeper on this Mac accepts the copied binary.
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 || true

echo "Creada: $APP (Python $VERSION)"
if [ "${1:-}" = "--install" ]; then
  DEST="$HOME/Applications/Heimdall.app"
  # macOS ties the Screen Recording permission to the app's signature, and
  # an ad-hoc signature changes whenever the bundle changes. Replacing an
  # identical bundle is harmless, but a changed one loses the permission,
  # so only replace it when something actually changed, and say so.
  if [ -d "$DEST" ] && diff -rq "$APP" "$DEST" >/dev/null 2>&1; then
    echo "~/Applications/Heimdall.app ya estaba al día; no se tocó."
  else
    HAD=$([ -d "$DEST" ] && echo 1 || echo 0)
    mkdir -p "$HOME/Applications"
    rm -rf "$DEST"
    cp -R "$APP" "$HOME/Applications/"
    echo "Instalada en ~/Applications/Heimdall.app"
    if [ "$HAD" = 1 ]; then
      echo "Aviso: la app cambió. Si ya le habías dado el permiso de Grabación de"
      echo "pantalla, macOS lo pide de nuevo: Ajustes del Sistema → Privacidad y"
      echo "seguridad → Grabación de pantalla y audio del sistema → quita Heimdall"
      echo "con «−», vuelve a agregarlo y abre la app otra vez."
    fi
  fi
fi
