#!/bin/sh
# Create Heimdall.app, a macOS launcher for running Heimdall from this folder.
#
# Why: launched as `python main.py`, macOS registers the process as
# "Python" (org.python.python). The Dock shows Python's icon when the app
# opens and again when it closes, and the menu bar says "Python". Inside a
# bundle with its own Info.plist, macOS shows Heimdall's name and icon the
# whole time.
#
# The bundle holds no code. It runs main.py and the .venv in this folder,
# so changes to the code show up without regenerating it. Regenerate only
# if you move the folder or recreate the .venv.
#
# Usage, from the repo root, after creating .venv (see README):
#   sh tools/make_macos_app.sh            # -> ~/Applications/Heimdall.app
#   sh tools/make_macos_app.sh <folder>   # -> <folder>/Heimdall.app
set -eu

[ "$(uname)" = "Darwin" ] || { echo "Solo para macOS." >&2; exit 1; }

REPO=$(cd "$(dirname "$0")/.." && pwd)
VENV_PY="$REPO/.venv/bin/python"
[ -x "$VENV_PY" ] || { echo "No existe $VENV_PY. Crea primero el .venv (ver README)." >&2; exit 1; }
[ -f "$REPO/branding/heimdall.icns" ] || { echo "Falta branding/heimdall.icns." >&2; exit 1; }

DEST_DIR=${1:-"$HOME/Applications"}
APP="$DEST_DIR/Heimdall.app"
VERSION=$(sed -n 's/^APP_VERSION = "\(.*\)"/\1/p' "$REPO/main.py")

# The GUI interpreter of the venv's base Python (framework build). Copying it
# into the bundle is what makes macOS treat the process as Heimdall.app;
# exec-ing the original would register it as Python.app again.
read -r PY_GUI SITE_PACKAGES <<EOF
$(env -u PYTHONPATH "$VENV_PY" -c 'import os, site, sys
gui = os.path.join(sys.base_prefix, "Resources/Python.app/Contents/MacOS/Python")
print(gui, site.getsitepackages()[0])')
EOF
[ -x "$PY_GUI" ] || { echo "No se encontró el intérprete gráfico de Python: $PY_GUI" >&2; exit 1; }

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$PY_GUI" "$APP/Contents/MacOS/python"
cp "$REPO/branding/heimdall.icns" "$APP/Contents/Resources/heimdall.icns"

cat > "$APP/Contents/MacOS/Heimdall" <<EOF
#!/bin/sh
# Generated by tools/make_macos_app.sh. Output goes to the log below,
# since an app opened from Finder or the Dock has no terminal.
cd "$REPO" || exit 1
export HEIMDALL_BUNDLE=1
mkdir -p "\$HOME/Library/Logs"
exec "\$(dirname "\$0")/python" -c '
import runpy, site, sys
site.addsitedir("$SITE_PACKAGES")
sys.argv = ["main.py"]
runpy.run_path("main.py", run_name="__main__")
' >>"\$HOME/Library/Logs/Heimdall.log" 2>&1
EOF
chmod +x "$APP/Contents/MacOS/Heimdall"

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Heimdall</string>
  <key>CFBundleDisplayName</key><string>Heimdall</string>
  <key>CFBundleIdentifier</key><string>io.github.jose-albarracin.heimdall</string>
  <key>CFBundleExecutable</key><string>Heimdall</string>
  <key>CFBundleIconFile</key><string>heimdall</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleVersion</key><string>$VERSION</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
EOF

# Make Finder and the Dock pick up the new icon right away.
touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP" 2>/dev/null || true

echo "Listo: $APP"
echo "Ábrela con doble clic o:  open \"$APP\""
echo "Registro: ~/Library/Logs/Heimdall.log"
